const init = {
    path: {
        GET: 'GET',
        POST: 'POST',
        PUT: 'PUT',
        DELETE: 'DELETE',
    },
    url: {
        login: '/api/app/login',
        getBanner: '/api/app/banner?',
        appIndex: '/api/app/recommend/appIndex?',
        courseClassify: '/api/app/courseClassify',
        courseBasis: '/api/app/courseBasis',
        courseInfo: '/api/app/courseInfo/basis_id=',
        otoCourseOptions: '/api/app/otoCourseOptions?',
        otoCourse: '/api/app/otoCourse?',
        getTeacher: '/api/app/teacher/',
        getTeacherInfo: '/api/app/teacher/info/',
        invite: '/api/app/teacher/invite',
        collect: 'api/app/teacher/collect/',
        mainCourse: '/api/app/teacher/mainCourse',
        collectKe: '/api/app/collect',
        cancel_collectKe: '/api/app/collect/cancel/',
        getUCenterInfo: '/api/app/getUCenterInfo?',
        coinRank: '/api/app/coin/coinRank?',
        pay: '/api/app/pay',
        feedback: '/api/app/feedback',
        userInfo: '/api/app/userInfo?',
        grade: '/api/app/vip/grade?',
        downOrder: '/api/app/order/downOrder',
        collectTeacher: '/api/app/collect?',
        attribute: '/api/app/module/attribute/1?',
        user: '/api/app/user',
        img: '/api/app/public/img',
        sonArea: '/api/app/sonArea/',
        myStudy: '/api/app/myStudy/',
        myStudyCourse: '/api/app/myStudy/course/',
        smsCode: '/api/app/smsCode',
        change_password: '/api/app/password',
    }
}

export default init